### ISSUE TITLE
`stripe samples create` –> panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bz-stripe** [stripe/stripe-cli#315]
### Issue
Following instructions on how to run Stripe Samples locally [0] produced a surprising stacktrace.

[0] https://github.com/stripe-samples/accept-a-card-payment#how-to-run-locally

### Expected Behavior
I believe the Stripe CLI should setup the project directory with an .env file of my API keys?

### Steps to reproduce
Run `stripe samples create accept-a-card-payment`

### Traceback
``` ruby
~/stripe/samples> stripe samples create accept-a-card-payment                                                                                
⣾ Downloading accept-a-card-payment panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16cb983]

goroutine 1 [running]:
github.com/stripe/stripe-cli/pkg/samples.(*SampleData).GitRepo(...)
        /home/travis/gopath/src/github.com/stripe/stripe-cli/pkg/samples/list.go:24
github.com/stripe/stripe-cli/pkg/samples.(*Samples).Initialize(0xc00051a160, 0x7ffeefbff52e, 0x15, 0xc0000a6000, 0xc000266280)
        /home/travis/gopath/src/github.com/stripe/stripe-cli/pkg/samples/samples.go:119 +0x143
github.com/stripe/stripe-cli/pkg/cmd/samples.(*CreateCmd).runCreateCmd(0xc00017b4d0, 0xc0001b1400, 0xc0001e53e0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/stripe/stripe-cli/pkg/cmd/samples/create.go:71 +0x469
github.com/spf13/cobra.(*Command).execute(0xc0001b1400, 0xc0001e5390, 0x1, 0x1, 0xc0001b1400, 0xc0001e5390)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1f6e9a0, 0x60c, 0xc0000e7f68, 0x16e0058)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/stripe/stripe-cli/pkg/cmd.Execute()
        /home/travis/gopath/src/github.com/stripe/stripe-cli/pkg/cmd/root.go:55 +0x9e
main.main()
        /home/travis/gopath/src/github.com/stripe/stripe-cli/cmd/stripe/main.go:6 +0x20
```

### Environment
macOS 10.14.6

**Comment by bz-stripe** [comment]
cc @adreyfus-stripe for visibility

**Comment by bz-stripe** [comment]
I noticed that accept-a-card-payment isn't in the list of available Samples

``` bash
~/stripe/samples> stripe samples list
A list of available Stripe Sample integrations:

adding-sales-tax
Learn how to use PaymentIntents to build a simple checkout flow
Repo: https://github.com/stripe-samples/adding-sales-tax

checkout-subscription-and-add-on
Uses Stripe Checkout to create a payment page that starts a subscription for a new customer
Repo: https://github.com/stripe-samples/checkout-subscription-and-add-on

placing-a-hold
Learn how to place a hold on a credit card (split auth / capture)
Repo: https://github.com/stripe-samples/placing-a-hold

payment-form-modal
How to implement Stripe Elements within a modal dialog
Repo: https://github.com/stripe-samples/payment-form-modal

saving-card-without-payment
How to build a form to save a credit card without taking a payment
Repo: https://github.com/stripe-samples/saving-card-without-payment
```

**Comment by adreyfus-stripe** [comment]
@bz-stripe My hunch is that you're on an older version that doesn't have the most up to date list of samples :( Try updating the CLI and running again

Not sure if we can do anything for that error message on that version

**Comment by tomer-stripe** [comment]
@bz-stripe what version are you running?

There's not much we can do retroactively but should handle that more gracefully in general

**Comment by bz-stripe** [comment]
Yup, I was on `stripe version 0.6.6 (beta)`. Upgrading via `brew upgrade stripe` updated the list of samples.

`stripe samples create accept-a-card-payment` successfully created the project.

But it didn't create a .env file the same way that `stripe samples create placing-a-hold` did. (Although the .env file in /placing-a-hold was where the server files expected it.)
