### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by tekord** [stripe/stripe-cli#662]
### Issue

The following command with a combination of 'forward-to' and 'headers' options produces the runtime error:

```
stripe listen --forward-to http://my-app.local/stripe/webhook --headers ACT-AS-USER=1

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/stripe/stripe-cli/pkg/proxy.convertToMapAndSanitize(0xc0003d2690, 0x1, 0x1, 0x156af40)
        D:/a/stripe-cli/stripe-cli/pkg/proxy/endpoint.go:190 +0x245
github.com/stripe/stripe-cli/pkg/proxy.NewEndpointClient(0xc00001e4b0, 0x23, 0xc0003d2690, 0x1, 0x1, 0x0, 0xc0001a97d0, 0x1, 0x1, 0xc000242160, ...)
        D:/a/stripe-cli/stripe-cli/pkg/proxy/endpoint.go:152 +0x88
github.com/stripe/stripe-cli/pkg/proxy.New(0xc000554750, 0xc0001a97d0, 0x1, 0x1, 0x2)
        D:/a/stripe-cli/stripe-cli/pkg/proxy/proxy.go:410 +0x3f1
github.com/stripe/stripe-cli/pkg/cmd.(*listenCmd).runListenCmd(0xc000146630, 0xc0001d9400, 0xc0001b4340, 0x0, 0x4, 0x0, 0x0)
        D:/a/stripe-cli/stripe-cli/pkg/cmd/listen.go:171 +0x5a5
github.com/spf13/cobra.(*Command).execute(0xc0001d9400, 0xc0001b4300, 0x4, 0x4, 0xc0001d9400, 0xc0001b4300)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1b40540, 0x70d, 0x60, 0xc000036060)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/stripe/stripe-cli/pkg/cmd.Execute()
        D:/a/stripe-cli/stripe-cli/pkg/cmd/root.go:64 +0xb1
main.main()
        D:/a/stripe-cli/stripe-cli/cmd/stripe/main.go:6 +0x27
```

There is no error if I put only 1 option (forward-to or headers) or write a different set of options. Looks like other options are work fine together, but not the combination of forward-to and headers options.

### Expected Behavior
No error expected.

### Steps to reproduce
Just run the given command above.

### Environment
Windows 10 x64

**Comment by gracegoo-stripe** [comment]
Hello,

Took a look and we are throwing that error as we parse the header because the parser expect the Key and Value to be delimited by `:` instead of `=`. The reason why the same error wasn't thrown with the header flag alone is because the header flag is not used when the forward option is not supplied with it. 

So the below should work: 
```
stripe listen --forward-to http://my-app.local/stripe/webhook --headers ACT-AS-USER:1
```

I'll update the help docs to make this more clear. Thanks again for reporting!
